services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data/db.sqlite:/app/db.sqlite
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - DB_PATH=/app/db.sqlite
